### ISSUE TITLE
Ansible failure & "fatal: could not create work tree dir '/var/www/mysite'"

### ISSUE THREAD

**Issue by Nick-Hope** [geerlingguy/drupal-vm#1853]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.0
"VirtualBox `vboxmanage --version`" (but I did have 5.2.20 r125813 (Qt5.6.2) already installed)
'ansible' is not recognized as an internal or external command, operable program or batch file.
```

### Your OS

 - **Windows** 10 Pro version 1511  (i.e. No WSL. I require this version for compatibility with one of my old programs.)

### Full console output

First `vagrant up` failure: https://gist.github.com/Nick-Hope/c143200dfe0f1215c8c90c059b6eac8a
Second `vagrant up` failure: https://gist.github.com/Nick-Hope/a0e6b78313e3b8d6d44615aef00cee05

### Summary

I was developing a website remotely on Pantheon. Now I wish to continue development locally in Drupal_VM for more speed and so I can install modules that can only be installed by Composer. I wish to later re-upload/push the site to Pantheon (or another host).

I would also like to convert to a Composer-managed site. I am not sure if that is possible at the same time as pulling in a Pantheon repo so my strategy has been to get the site going in Drupal VM and then follow [Jeff's tutorial about converting to use Composer](https://www.jeffgeerling.com/blog/2018/converting-non-composer-drupal-codebase-use-composer).

The command that Pantheon give me to clone my remote site's repo is: `git clone ssh://codeserver.dev.111cafdf-750a-4ce6-a635-f0f80e6abcd8@codeserver.dev.111cafdf-750a-4ce6-a635-f0f80e6abcd8.drush.in:2222/~/repository.git see-life`.

Wanting speed, I followed Jeff's tutorial, _[Drupal VM on Windows - a fast container for BLT project development](https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development)_, but with a few updates/mods to config.yml including the use of php 7.2 & nginx, to be the same as my Pantheon environment. This is my config.yml:

```
---
vagrant_synced_folders: []
vagrant_synced_folder_default_type: ""

vagrant_hostname: local.see-life.com
vagrant_machine_name: see-life
vagrant_ip: 192.168.88.25

drupal_deploy: true
drupal_deploy_repo: "ssh://codeserver.dev.111cafdf-750a-4ce6-a635-f0f80e6abcd8@codeserver.dev.111cafdf-750a-4ce6-a635-f0f80e6abcd8.drush.in:2222/~/repository.git"
drupal_deploy_version: master
drupal_deploy_update: true
drupal_deploy_dir: "/var/www/see-life"
drupal_deploy_accept_hostkey: yes
drupal_core_path: "{{ drupal_deploy_dir }}/docroot"
ssh_home: "{{ drupal_deploy_dir }}"

drupal_build_composer: false
drupal_composer_path: false
drupal_build_composer_project: false
drupal_install_site: false

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
  # For reverse-mount Samba share.
  - "137"
  - "138"
  - "139"
  - "445"

# Run the setup script.
pre_provision_scripts:
  - "../examples/scripts/setup.sh"

# BLT-specific overrides.
vagrant_box: geerlingguy/ubuntu1604

drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

configure_drush_aliases: false

# Use PHP 5.6.
php_version: "7.2"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - imagemagick

# Jeff had this at 4.x in Windows speed tutorial
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: npm
drupalvm_user: vagrant
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  - adminer
  - drupalconsole
  - drush
  - mailhog
  - nodejs
  - pimpmylog
  - xdebug

# XDebug configuration. XDebug is disabled by default for better performance. Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
# Change this value to 1 in order to enable xdebug on the cli.
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: VSCODE
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"

drupalvm_webserver: nginx
```
I already had VirtualBox Version 5.2.20 r125813 (Qt5.6.2) installed for another purpose.

I started Cmder as admin and ran `vagrant up` and got a very long error that started like this:

```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [see-life]: FAILED! => {"cache_update_time": 1540903403, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'php7.2' 'php7.2-apcu'......
```
...and finally `Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.` Full console output is linked above.

I then ran `vagrant destroy` and ran `vagrant up` again. This time better but then this error:

```
TASK [geerlingguy.drupal : Check out Drupal to the docroot.] *******************
fatal: [see-life]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin '' /var/www/see-life", "msg": "fatal: could not create work tree dir '/var/www/see-life': Permission denied", "rc": 128, "stderr": "fatal: could not create work tree dir '/var/www/see-life': Permission denied\n", "stderr_lines": ["fatal: could not create work tree dir '/var/www/see-life': Permission denied"], "stdout": "", "stdout_lines": []}
```
...and finally a `Ansible failed to complete successfully...` message again. More console output is in the 2nd link above.

Now `ansible --v` returns `'ansible' is not recognized as an internal or external command,
operable program or batch file.`. That implies that Ansible didn't get installed.

Further, my `drupal_deploy_repo` may well be incorrect, as I am not sure which part of the code from Pantheon I should enter in there.

Any help to get this working would be greatly appreciated.

**Comment by geerlingguy** [comment]
Better formatting for the two errors:

```
Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-mbstring_7.2.11-3+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
", "rc": 100, "stderr": "E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-mbstring_7.2.11-3+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

And second error:

```
$ /usr/bin/git clone --origin origin /var/www/see-life
fatal: could not create work tree dir '/var/www/see-life': Permission denied
```

The first error is fairly common, usually a temporary network issue or an outage with the repo. It looks like that was resolved on the second go-round.

For the `/var/www/see-life` issue, it looks like that's a basic permissions issue.

Note—it seems like you have `vagrant_synced_folders` set to `[]` (which means there are no shared folders inside the VM). This is good for performance, but I'm wondering if it's an issue where the folder doesn't even exist in the VM, or it's getting created but under the root user or something.

Could you log into the VM (`vagrant ssh`), then run `ls -lah /var/www/` and show the results here? Should show file ownership and maybe it's as easy as running a command to fix the permissions, or it could be traced back to a bug somewhere.

**Comment by Nick-Hope** [comment]
Hi Jeff. Thanks for the reply. I've reverted to Dev Desktop for now (after an adventure with Lando on Ubuntu) because of the various issues I was having and I no longer have the Drupal VM version of the site that was giving me the errors described in this post. For what it's worth I do still have an older version of the site that I created previously with Drupal VM (without bothering about the "fast method", composer management, drush versions etc.) and it seems to be working. The output from that one is here:
```
vagrant@drupalvm:/var/www/drupalvm/drupal/web$ ls -lah /var/www/
total 24K
drwxr-xr-x  5 root    root    4.0K Nov  1 07:30 .
drwxr-xr-x 12 root    root    4.0K Nov  1 07:14 ..
drwxr-xr-x  2 root    root    4.0K Nov  1 07:30 dashboard
drwxrwxrwx  1 vagrant vagrant 8.0K Nov  1 08:17 drupalvm
drwxr-xr-x  2 root    root    4.0K Nov  1 07:18 html```
