### ISSUE TITLE
New DrupalConsole installer instructions.

### ISSUE THREAD

**Issue by jmolivas** [geerlingguy/drupal-vm#335]
@geerlingguy: Since latest changes on the site and the project the instructions for setting up Drupal Console, have changed I just copied instructions on the home page at http://www.drupalconsole.com :

```
# Run this in your terminal to get the latest Console version:
curl http://drupalconsole.com/installer -L -o drupal.phar

# Or if you don't have curl:
php -r "readfile('http://drupalconsole.com/installer');" > drupal.phar

# Accessing from anywhere on your system:
mv drupal.phar /usr/local/bin/drupal

# Copy configuration files to user home directory:
drupal init [--override]
```

**Comment by oxyc** [comment]
Not entirely comfortable with fetching an executable over http

**Comment by jmolivas** [comment]
Since we  move the site to a PassS, we are in the process to implement https, I will keep you updated.

**Comment by geerlingguy** [comment]
@oxyc ++ - Since console is now configurable, until it's https, you can exclude it from the list of `installed_extras` if you'd like until you're in a trustedlocation/network.

**Comment by jmolivas** [comment]
You can manually `curl` the latest version from the project releases page at: https://github.com/hechoendrupal/DrupalConsole/releases

NOTE: This is what we do on the installer URL, grab the `drupal.phar` from github .

**Comment by geerlingguy** [comment]
And IIRC (don't have time to verify right now), I have the geerlingguy.drupal-console role set to do it this way, instead of grabbing the installer direct from the DC website, for that very reason. But might need to make some changes there too, we'll see.

**Comment by geerlingguy** [comment]
This will need to be fixed in the `geerlingguy.drupal-console` role.

**Comment by geerlingguy** [comment]
Merged https://github.com/geerlingguy/ansible-role-drupal-console/pull/5 to fix this.

**Comment by geerlingguy** [comment]
This has been fixed upstream. Please make sure you run `sudo ansible-galaxy install -r provisioning/requirements.yml --force` to get the latest version of the role.

**Comment by jmolivas** [comment]
@oxyc @geerlingguy: We enabled SSL on the site. new installer instructions using `https`:

```
# Run this in your terminal to get the latest project version:
curl https://drupalconsole.com/installer -L -o drupal.phar
```

**Comment by geerlingguy** [comment]
@jmolivas - Thanks for the quick turnaround! Updated the role in the above issue.

**Comment by elju** [comment]
This still appears to be broken for me, I am getting the following error
```
TASK: [geerlingguy.drupal-console | Run Drupal Console init.] *****************
<127.0.0.1> REMOTE_MODULE command php /usr/local/bin/drupal init creates=~/.console #USE_SHELL
failed: [drupaldev] => {"changed": true, "cmd": "php /usr/local/bin/drupal init", "delta": "0:00:00.187567", "end": "2015-12-16 18:12:03.547324", "rc": 255, "start": "2015-12-16 18:12:03.359757", "warnings": []}
stderr: Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory
PHP Parse error:  syntax error, unexpected '==' (T_IS_EQUAL), expecting ')' in phar:///usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php on line 48
```
using the debian box

**Comment by jmolivas** [comment]
@elju Which version of DC is causing this issue?. We fixed Drupal-VM, issues on latest release and must be working now.

**Comment by geerlingguy** [comment]
@elju I'm guessing something is broken with your PHP installation... if you log into the VM and do anything else (e.g. `php -i`), does that work?

**Comment by elju** [comment]
@geerlingguy `php -i` seems to be working fine. @jmolivas this was downloaded today via `curl https://drupalconsole.com/installer` , unsure of how to check the version number, but it seems like that should be the newest version.

**Comment by jmolivas** [comment]
@elju:  Just by running any of `drupal --version` or just `drupal`
* drupal --version 
```
Drupal Console version 0.9.10
```
* drupal
```
drupal

Drupal Console (0.9.10) | Supports Drupal 8.0.1
===============================================

Copy configuration files to user home directory.

   drupal init [--override]

Download, install and serve Drupal 8

   drupal chain --file=~/.console/chain/quick-start.yml

Create a new Drupal project

   drupal site:new drupal8.dev 8.0.1

Install a Drupal project

   drupal site:install

Lists all available commands

   drupal list

Update project to the latest version.
-------------------------------------

   drupal self-update
```

**Comment by elju** [comment]
@jmolivas both of those commands are just throwing the same error, but I'm 99% sure this is the newest version:

```
vagrant@dev/usr/local/bin >: drupal
PHP Parse error:  syntax error, unexpected '==' (T_IS_EQUAL), expecting ')' in phar:///usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php on line 48
vagrant@dev/usr/local/bin >: drupal --version
PHP Parse error:  syntax error, unexpected '==' (T_IS_EQUAL), expecting ')' in phar:///usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php on line 48
```

**Comment by jmolivas** [comment]
@elju: I will take a look at the code and ping you back.

**Comment by elju** [comment]
Thanks! My php version is `PHP 5.4.45-0+deb7u2` and the box that I'm on Debian wheezy if that's helpful

**Comment by elju** [comment]
yeah, I can reproduce this from scratch with
```
vagrant init puphpet/debian75-x64
vagrant ssh
sudo apt-get update
sudo apt-get install php5-cli curl
sudo curl https://drupalconsole.com/installer -L -o /usr/local/bin/drupal
sudo chmod +x /usr/local/bin/drupal
drupal --version
PHP Parse error:  syntax error, unexpected '==' (T_IS_EQUAL), expecting ')' in phar:///usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php on line 48
```

Should I move this over to an issue on drupal-console?

**Comment by geerlingguy** [comment]
Yes, I'd move this to drupal-console project. I don't even know if PHP 5.4 is supported... I thought Console required 5.5+.

**Comment by jmolivas** [comment]
Drupal Console requires `"php": ">=5.5.9",` 
https://github.com/hechoendrupal/DrupalConsole/blob/master/composer.json#L39
Same as Drupal 8 
https://github.com/drupal/drupal/blob/8.0.x/core/composer.json#L7

**Comment by elju** [comment]
Oh, this is failing because the php role using apt-get, but on debian wheezy, apt-get only installs 5.4. Works fine on newer versions. Sorry for wasting your time.

**Comment by jmolivas** [comment]
@elju I glad to read it works ;)

**Comment by chriscalip** [comment]
@jmolivas 
This year vlad with drupalconsole has stopped working because of drupalconsole stopped being a standalone.
According to article https://drupalconsole.com/articles/drupalconsole-launcher-a-stand-alone-full-cli-application is back being a standalone.
Current vlad snapshot still is unable to install drupalconsole. Any thoughts?

**Comment by jmolivas** [comment]
@chriscalip is a stand alone CLI but provide a limited number of commands you still need to install per-site more info about it at the docs => https://docs.drupalconsole.com/en/getting/project.html

**Comment by jmolivas** [comment]
how do I test vlad @chriscalip ?

**Comment by chriscalip** [comment]
@jmolivas Ahh. I thought since you were in this thread I assumed that you are familiar with vlad use.
https://vlad-docs.readthedocs.io/en/latest/usage/installation/
After installation and `vagrant ssh`.
`
✝ vagrant@d8vlad ✝ /var/www/site/docroot
$ drupal
 [ERROR] Drupal Console is not installed at:
 You must execute the following composer commands:

 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
 composer update drupal/console --with-dependencies

✝ vagrant@d8vlad ✝ /var/www/site/docroot
$
`

**Comment by oxyc** [comment]
@chriscalip fyi this is the Drupal VM issue queue :)

**Comment by chriscalip** [comment]
@oxyc @jmolivas  Right, I am sorry this issue was in the vlad issue queue; and this is a drupal-vm issue.
