### ISSUE TITLE
Drupalvm sync folder not showing on host machine

### ISSUE THREAD

**Issue by mooru** [geerlingguy/drupal-vm#734]
I have done 2 installs of drupalvm from the git clone but the sync folder has not shown up for either installations (ie under /Users/me/Sites/drupalvm/drupal)
vagrant version 1.8.3
Virtualbox version 5.0.20
MacOSX 10.11.5

I also didn't changed the config.yml file

I have done a second vagrant destroy and vagrant up still no changes. when  i do vagrant ssh i can see the drupal files installed.

**Comment by geerlingguy** [comment]
The only difference between my environments (Windows 10 / Mac OS X 10.11) and yours seems to be that I have Vagrant 1.8.1, while you have 1.8.3.

Over in #683 you had shown that the synced dir seems to not be created, so I'm thinking we can maybe test some more troubleshooting to see where exactly that directory is being generated!

Inside the VM, can you run `sudo cat /proc/mounts` and give the output? Maybe the synced dir isn't being mounted...

**Comment by mooru** [comment]
I ran that command and this is the output. unfortunately my linux skills are not there yet

sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=490136k,nr_inodes=122534,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=101620k,mode=755 0 0
/dev/mapper/vagrant--vg-root / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd,nsroot=/ 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,nsroot=/ 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio,nsroot=/ 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,nsroot=/ 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,nsroot=/ 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices,nsroot=/ 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory,nsroot=/ 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio,nsroot=/ 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,nsroot=/ 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct,nsroot=/ 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer,nsroot=/ 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
/dev/sda1 /boot ext2 rw,relatime,block_validity,barrier,user_xattr,acl 0 0
192.168.88.1:/Users/martinoru/Sites/drupalvm /vagrant nfs rw,relatime,vers=3,rsize=8192,wsize=8192,namlen=255,hard,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=192.168.88.1,mountvers=3,mountport=1014,mountproto=udp,local_lock=none,addr=192.168.88.1 0 0
tmpfs /run/user/900 tmpfs rw,nosuid,nodev,relatime,size=101620k,mode=700,uid=900,gid=900 0 0

**Comment by mooru** [comment]
inside the vm i ram mount drupalvm from the /var/www directory and i get this error 
mount: can't find /var/www/drupalvm in /etc/fstab

could that be it

**Comment by geerlingguy** [comment]
@mooru no, it looks like there's a mount for the /vagrant directory at least—see:

```
192.168.88.1:/Users/martinoru/Sites/drupalvm /vagrant nfs 
```

But there's no mount for the `.` share, so it seems Vagrant may not be setting that up at all :/

Can you delete your `config.yml` file entirely, then provision again using all the defaults as in `default.config.yml`, and see what happens?

**Comment by mooru** [comment]
OK. i will try that and see

**Comment by mooru** [comment]
I have deleted the config.yml file, duplicated it again and vagrant provision and it didn't work. i also ran vagrant provision with the default.config.yml and it still didn't work

**Comment by trwill** [comment]
+1

**Comment by oxyc** [comment]
@mooru if you have a box provisioned already could you run the following an post that massive debug dump that vagrant outputs:

```sh
vagrant halt
vagrant up --debug
```

If it helps I'm specifically interested in what comes after `==> drupalvm: Exporting NFS shared folders...`

This is my own output:

```
==> drupalvm_project: Exporting NFS shared folders...
DEBUG host: Searching for cap: nfs_export
DEBUG host: Checking in: darwin
DEBUG host: Checking in: bsd
DEBUG host: Found cap: nfs_export in bsd
 INFO host: Execute capability: nfs_export [#<Vagrant::Environment: /Users/cindy/Projects/Personal/drupal-vm>, #<Vagrant::UI::Prefixed:0x00000102516078 @logger=#<Log4r::Logger:0x00000102516028 @fullname="vagrant::ui::interface", @outputters=[], @additive=true, @name="interface", @path="vagrant::ui", @parent=#<Log4r::Logger:0x0000010246dfb8 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000010243c080 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x0000010243c008>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000001024352d0 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000010246dea0 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @opts={}, @stdin=#<IO:<STDIN>>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @prefix=:drupalvm_project, @ui=#<Vagrant::UI::Colored:0x00000102103698 @logger=#<Log4r::Logger:0x000001021035d0 @fullname="vagrant::ui::interface", @outputters=[], @additive=true, @name="interface", @path="vagrant::ui", @parent=#<Log4r::Logger:0x0000010246dfb8 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000010243c080 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x0000010243c008>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000001024352d0 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000010246dea0 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @opts={:color=>:default}, @stdin=#<IO:<STDIN>>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @lock=#<Mutex:0x0000010207bf90>>>, "2046c663-484c-4762-a214-435761bc61db", ["192.168.99.88"], {"/var/www/drupalvm"=>{:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/cindy/Projects/Personal/drupal-vm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"1306290540"}, "/vagrant"=>{:type=>:nfs, :guestpath=>"/vagrant", :hostpath=>"/Users/cindy/Projects/Personal/drupal-vm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"1306290540"}, "vagrant-cache"=>{:id=>"vagrant-cache", :type=>:nfs, :mount_options=>["rw", "vers=3", "tcp", "nolock"], :guestpath=>"/tmp/vagrant-cache", :hostpath=>"/Users/cindy/.vagrant.d/cache/geerlingguy/ubuntu1404", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"222177124"}}] (darwin)
DEBUG host: Searching for cap: nfs_exports_template
DEBUG host: Checking in: darwin
DEBUG host: Checking in: bsd
DEBUG host: Found cap: nfs_exports_template in bsd
 INFO host: Execute capability: nfs_exports_template [#<Vagrant::Environment: /Users/cindy/Projects/Personal/drupal-vm>] (darwin)
DEBUG host: Searching for cap: nfs_restart_command
DEBUG host: Checking in: darwin
DEBUG host: Checking in: bsd
DEBUG host: Found cap: nfs_restart_command in bsd
 INFO host: Execute capability: nfs_restart_command [#<Vagrant::Environment: /Users/cindy/Projects/Personal/drupal-vm>] (darwin)
 INFO subprocess: Starting process: ["/sbin/nfsd", "checkexports"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG bsd: Compiling map of sub-directories for NFS exports...
 INFO bsd: Exporting the following for NFS...
 INFO bsd: NFS DIR: ["/Users/cindy/.vagrant.d/cache/geerlingguy/ubuntu1404"]
 INFO bsd: NFS OPTS: {:id=>"vagrant-cache", :type=>:nfs, :mount_options=>["rw", "vers=3", "tcp", "nolock"], :guestpath=>"/tmp/vagrant-cache", :hostpath=>"/Users/cindy/.vagrant.d/cache/geerlingguy/ubuntu1404", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"222177124", :bsd__nfs_options=>["alldirs", "mapall=501:20"], :bsd__compiled_nfs_options=>"-alldirs -mapall=501:20"}
 INFO bsd: NFS DIR: ["/Users/cindy/Projects/Personal/drupal-vm"]
 INFO bsd: NFS OPTS: {:type=>:nfs, :guestpath=>"/vagrant", :hostpath=>"/Users/cindy/Projects/Personal/drupal-vm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"1306290540", :bsd__nfs_options=>["alldirs", "mapall=501:20"], :bsd__compiled_nfs_options=>"-alldirs -mapall=501:20"}
 INFO interface: info: Preparing to edit /etc/exports. Administrator privileges will be required...
 INFO interface: info: ==> drupalvm_project: Preparing to edit /etc/exports. Administrator privileges will be required...
==> drupalvm_project: Preparing to edit /etc/exports. Administrator privileges will be required...
 INFO environment: Released process lock: nfs-export
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO interface: info: Mounting NFS shared folders...
 INFO interface: info: ==> drupalvm_project: Mounting NFS shared folders...
==> drupalvm_project: Mounting NFS shared folders...
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: mount_nfs_folder
DEBUG guest: Checking in: ubuntu
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: mount_nfs_folder in linux
 INFO guest: Execute capability: mount_nfs_folder [#<Vagrant::Machine: drupalvm_project (VagrantPlugins::ProviderVirtualBox::Provider)>, "192.168.99.1", {"/var/www/drupalvm"=>{:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/cindy/Projects/Personal/drupal-vm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"1306290540"}, "/vagrant"=>{:type=>:nfs, :guestpath=>"/vagrant", :hostpath=>"/Users/cindy/Projects/Personal/drupal-vm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"1306290540"}, "vagrant-cache"=>{:id=>"vagrant-cache", :type=>:nfs, :mount_options=>["rw", "vers=3", "tcp", "nolock"], :guestpath=>"/tmp/vagrant-cache", :hostpath=>"/Users/cindy/.vagrant.d/cache/geerlingguy/ubuntu1404", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"222177124"}}] (ubuntu)
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: shell_expand_guest_path
DEBUG guest: Checking in: ubuntu
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: shell_expand_guest_path in linux
 INFO guest: Execute capability: shell_expand_guest_path [#<Vagrant::Machine: drupalvm_project (VagrantPlugins::ProviderVirtualBox::Provider)>, "/var/www/drupalvm"] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf /var/www/drupalvm (sudo=false)
DEBUG ssh: stdout:
/var/www/drupalvm
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mkdir -p /var/www/drupalvm (sudo=true)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: stdout:
/tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mount -o '' 192.168.99.1:'/Users/cindy/Projects/Personal/drupal-vm' /var/www/drupalvm (sudo=true)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: stdout:
/tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: if command -v /sbin/init &>/dev/null && /sbin/init --version | grep upstart &>/dev/null; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT='/var/www/drupalvm'
fi
 (sudo=true)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: stdout:
/tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: shell_expand_guest_path
DEBUG guest: Checking in: ubuntu
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: shell_expand_guest_path in linux
 INFO guest: Execute capability: shell_expand_guest_path [#<Vagrant::Machine: drupalvm_project (VagrantPlugins::ProviderVirtualBox::Provider)>, "/vagrant"] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf /vagrant (sudo=false)
DEBUG ssh: stdout:
/vagrant
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mkdir -p /vagrant (sudo=true)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: stdout:
/tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-JksLPSH3nX/agent.1049
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mount -o 'vers=3,udp' 192.168.99.1:'/Users/cindy/Projects/Personal/drupal-vm' /vagrant (sudo=true)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Exit status: 0
```

**Comment by mooru** [comment]
I ran vagrant up --debug and this is the output

`DEBUG host: Searching for cap: nfs_export
DEBUG host: Checking in: darwin
DEBUG host: Checking in: bsd
DEBUG host: Found cap: nfs_export in bsd
 INFO host: Execute capability: nfs_export [#<Vagrant::Environment: /Users/martinoru/Sites/drupalvm>, #<Vagrant::UI::Prefixed:0x00000101de87b0 @logger=#<Log4r::Logger:0x00000101de8738 @fullname="vagrant::ui::interface", @outputters=[], @additive=true, @name="interface", @path="vagrant::ui", @parent=#<Log4r::Logger:0x00000101b32b10 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x00000100bf9ea0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000100bf9e28>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x00000100bf2f88 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000101b329f8 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @opts={}, @stdin=#<IO:<STDIN>>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @prefix=:drupalvm, @ui=#<Vagrant::UI::Colored:0x00000100b802f8 @logger=#<Log4r::Logger:0x00000100b80230 @fullname="vagrant::ui::interface", @outputters=[], @additive=true, @name="interface", @path="vagrant::ui", @parent=#<Log4r::Logger:0x00000101b32b10 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x00000100bf9ea0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000100bf9e28>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x00000100bf2f88 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000101b329f8 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @opts={:color=>:default}, @stdin=#<IO:<STDIN>>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @lock=#<Mutex:0x00000100c48ca8>>>, "d3e20ea3-1e03-470d-abce-d24872c40163", ["192.168.88.88"], {"/var/www/drupalvm"=>{:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/martinoru/Sites/drupalvm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"2000371556"}, "/vagrant"=>{:type=>:nfs, :guestpath=>"/vagrant", :hostpath=>"/Users/martinoru/Sites/drupalvm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"2000371556"}}] (darwin)
DEBUG host: Searching for cap: nfs_exports_template
DEBUG host: Checking in: darwin
DEBUG host: Checking in: bsd
DEBUG host: Found cap: nfs_exports_template in bsd
 INFO host: Execute capability: nfs_exports_template [#<Vagrant::Environment: /Users/martinoru/Sites/drupalvm>] (darwin)
DEBUG host: Searching for cap: nfs_restart_command
DEBUG host: Checking in: darwin
DEBUG host: Checking in: bsd
DEBUG host: Found cap: nfs_restart_command in bsd
 INFO host: Execute capability: nfs_restart_command [#<Vagrant::Environment: /Users/martinoru/Sites/drupalvm>] (darwin)
 INFO subprocess: Starting process: ["/sbin/nfsd", "checkexports"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG bsd: Compiling map of sub-directories for NFS exports...
 INFO bsd: Exporting the following for NFS...
 INFO bsd: NFS DIR: ["/Users/martinoru/Sites/drupalvm"]
 INFO bsd: NFS OPTS: {:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/martinoru/Sites/drupalvm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"2000371556", :bsd__nfs_options=>["alldirs", "mapall=501:20"], :bsd__compiled_nfs_options=>"-alldirs -mapall=501:20"}
 INFO interface: info: Preparing to edit /etc/exports. Administrator privileges will be required...
 INFO interface: info: ==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...`

**Comment by oxyc** [comment]
Looks correct so far. After you input the password, what follows? I'm looking for these:

> DEBUG guest: Found cap: mount_nfs_folder in linux
 INFO guest: Execute capability: mount_nfs_folder [#<Vagrant::Machine: drupalvm_project (VagrantPlugins::ProviderVirtualBox::Provider)>, "192.168.99.1", {"/var/www/drupalvm"=>{:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/cindy/Projects/Personal/drupal-vm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"1306290540"}, "/vagrant"=>{:type=>:nfs, :guestpath=>"/vagrant", :hostpath=>"/Users/cindy/Projects/Personal/drupal-vm", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"1306290540"}, "vagrant-cache"=>{:id=>"vagrant-cache", :type=>:nfs, :mount_options=>["rw", "vers=3", "tcp", "nolock"], :guestpath=>"/tmp/vagrant-cache", :hostpath=>"/Users/cindy/.vagrant.d/cache/geerlingguy/ubuntu1404", :disabled=>false, :__vagrantfile=>true, :map_uid=>501, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"222177124"}}] (ubuntu)

>  INFO ssh: Execute: mount -o '' 192.168.99.1:'/Users/cindy/Projects/Personal/drupal-vm' /var/www/drupalvm (sudo=true)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

**Comment by alesrebec** [comment]
I can reproduce this error with default config.yml file (local_path ".")

Here is my vagrant up --debug:

`==> bs8: Exporting NFS shared folders...

DEBUG host: Searching for cap: nfs_export

DEBUG host: Checking in: darwin

DEBUG host: Checking in: bsd

DEBUG host: Found cap: nfs_export in bsd

 INFO host: Execute capability: nfs_export [#<Vagrant::Environment: /Users/alesrebec/Projects/drupal-vm/bs8>, #<Vagrant::UI::Prefixed:0x0000010241ced8 @logger=#<Log4r::Logger:0x0000010241ce88 @fullname="vagrant::ui::interface", @outputters=[], @additive=true, @name="interface", @path="vagrant::ui", @parent=#<Log4r::Logger:0x00000100c60ee8 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x00000100c33808 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000100c33790>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x00000100c30950 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000100c60da8 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @opts={}, @stdin=#<IO:<STDIN>>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @prefix=:bs8, @ui=#<Vagrant::UI::Colored:0x000001021de8d8 @logger=#<Log4r::Logger:0x000001021de860 @fullname="vagrant::ui::interface", @outputters=[], @additive=true, @name="interface", @path="vagrant::ui", @parent=#<Log4r::Logger:0x00000100c60ee8 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x00000100c33808 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000100c33790>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x00000100c30950 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000100c60da8 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @opts={:color=>:default}, @stdin=#<IO:<STDIN>>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @lock=#<Mutex:0x000001021a6118>>>, "5fc8bfff-d91a-479b-af07-fdad3cdb5873", ["192.168.88.108"], {"/var/www/drupalvm"=>{:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/alesrebec/Projects/drupal-vm/bs8", :disabled=>false, :__vagrantfile=>true, :map_uid=>502, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"3446242676"}, "/vagrant"=>{:type=>:nfs, :guestpath=>"/vagrant", :hostpath=>"/Users/alesrebec/Projects/drupal-vm/bs8", :disabled=>false, :__vagrantfile=>true, :map_uid=>502, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"3446242676"}}] (darwin)

DEBUG host: Searching for cap: nfs_exports_template

DEBUG host: Checking in: darwin

DEBUG host: Checking in: bsd

DEBUG host: Found cap: nfs_exports_template in bsd

 INFO host: Execute capability: nfs_exports_template [#<Vagrant::Environment: /Users/alesrebec/Projects/drupal-vm/bs8>] (darwin)

DEBUG host: Searching for cap: nfs_restart_command

DEBUG host: Checking in: darwin

DEBUG host: Checking in: bsd

DEBUG host: Found cap: nfs_restart_command in bsd

 INFO host: Execute capability: nfs_restart_command [#<Vagrant::Environment: /Users/alesrebec/Projects/drupal-vm/bs8>] (darwin)

 INFO subprocess: Starting process: ["/sbin/nfsd", "checkexports"]

DEBUG subprocess: Command not in installer, not touching env vars.

 INFO subprocess: Command not in installer, restoring original environment...

DEBUG subprocess: Selecting on IO

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000

DEBUG subprocess: Exit status: 0

DEBUG bsd: Compiling map of sub-directories for NFS exports...

 INFO bsd: Exporting the following for NFS...

 INFO bsd: NFS DIR: ["/Users/alesrebec/Projects/drupal-vm/bs8"]

 INFO bsd: NFS OPTS: {:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/alesrebec/Projects/drupal-vm/bs8", :disabled=>false, :__vagrantfile=>true, :map_uid=>502, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"3446242676", :bsd__nfs_options=>["alldirs", "mapall=502:20"], :bsd__compiled_nfs_options=>"-alldirs -mapall=502:20"}

 INFO interface: info: Preparing to edit /etc/exports. Administrator privileges will be required...

 INFO interface: info: ==> bs8: Preparing to edit /etc/exports. Administrator privileges will be required...

==> bs8: Preparing to edit /etc/exports. Administrator privileges will be required...

 INFO environment: Released process lock: nfs-export

DEBUG environment: Attempting to acquire process-lock: dotlock

 INFO environment: Acquired process lock: dotlock

 INFO environment: Released process lock: dotlock

 INFO interface: info: Mounting NFS shared folders...

 INFO interface: info: ==> bs8: Mounting NFS shared folders...

==> bs8: Mounting NFS shared folders...

DEBUG ssh: Checking whether SSH is ready...

DEBUG ssh: Re-using SSH connection.

 INFO ssh: SSH is ready!

DEBUG ssh: Re-using SSH connection.

 INFO ssh: Execute:  (sudo=false)

DEBUG ssh: Exit status: 0

DEBUG guest: Searching for cap: mount_nfs_folder

DEBUG guest: Checking in: ubuntu

DEBUG guest: Checking in: debian

DEBUG guest: Checking in: linux

DEBUG guest: Found cap: mount_nfs_folder in linux

 INFO guest: Execute capability: mount_nfs_folder [#<Vagrant::Machine: bs8 (VagrantPlugins::ProviderVirtualBox::Provider)>, "192.168.88.1", {"/var/www/drupalvm"=>{:type=>:nfs, :rsync__auto=>"true", :rsync__exclude=>nil, :rsync__args=>["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"], :id=>nil, :create=>true, :mount_options=>[], :guestpath=>"/var/www/drupalvm", :hostpath=>"/Users/alesrebec/Projects/drupal-vm/bs8", :disabled=>false, :__vagrantfile=>true, :map_uid=>502, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"3446242676"}, "/vagrant"=>{:type=>:nfs, :guestpath=>"/vagrant", :hostpath=>"/Users/alesrebec/Projects/drupal-vm/bs8", :disabled=>false, :__vagrantfile=>true, :map_uid=>502, :map_gid=>20, :nfs_udp=>true, :nfs_version=>3, :uuid=>"3446242676"}}] (ubuntu)

DEBUG ssh: Checking whether SSH is ready...

DEBUG ssh: Re-using SSH connection.

 INFO ssh: SSH is ready!

DEBUG ssh: Re-using SSH connection.

 INFO ssh: Execute:  (sudo=false)

DEBUG ssh: Exit status: 0

DEBUG guest: Searching for cap: shell_expand_guest_path

DEBUG guest: Checking in: ubuntu

DEBUG guest: Checking in: debian

DEBUG guest: Checking in: linux

DEBUG guest: Found cap: shell_expand_guest_path in linux

 INFO guest: Execute capability: shell_expand_guest_path [#<Vagrant::Machine: bs8 (VagrantPlugins::ProviderVirtualBox::Provider)>, "/var/www/drupalvm"] (ubuntu)

DEBUG ssh: Re-using SSH connection.

 INFO ssh: Execute: echo; printf /var/www/drupalvm (sudo=false)

DEBUG ssh: stdout: 



DEBUG ssh: stdout: /var/www/drupalvm

DEBUG ssh: Exit status: 0

DEBUG ssh: Checking whether SSH is ready...

DEBUG ssh: Re-using SSH connection.

 INFO ssh: SSH is ready!

DEBUG ssh: Re-using SSH connection.

 INFO ssh: Execute:  (sudo=false)

DEBUG ssh: Exit status: 0

DEBUG guest: Searching for cap: shell_expand_guest_path

DEBUG guest: Checking in: ubuntu

DEBUG guest: Checking in: debian

DEBUG guest: Checking in: linux

DEBUG guest: Found cap: shell_expand_guest_path in linux

 INFO guest: Execute capability: shell_expand_guest_path [#<Vagrant::Machine: bs8 (VagrantPlugins::ProviderVirtualBox::Provider)>, "/vagrant"] (ubuntu)

DEBUG ssh: Re-using SSH connection.

 INFO ssh: Execute: echo; printf /vagrant (sudo=false)

DEBUG ssh: stdout: 



DEBUG ssh: stdout: /vagrant

DEBUG ssh: Exit status: 0

DEBUG ssh: Re-using SSH connection.

 INFO ssh: Execute: mkdir -p '/var/www/drupalvm'

**mount -o  '192.168.88.1:/Users/alesrebec/Projects/drupal-vm/bs8' '/var/www/drupalvm'**

if command -v /sbin/init && /sbin/init --version | grep upstart; then

  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT='/var/www/drupalvm'

fi



mkdir -p '/vagrant'

mount -o vers=3,udp '192.168.88.1:/Users/alesrebec/Projects/drupal-vm/bs8' '/vagrant'

if command -v /sbin/init && /sbin/init --version | grep upstart; then

  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT='/vagrant'

fi

 (sudo=true)

DEBUG ssh: Re-using SSH connection.

 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)

DEBUG ssh: stderr: mesg: ttyname failed: Inappropriate ioctl for device



DEBUG ssh: stdout: 



DEBUG ssh: stdout: /tmp/ssh-4fSUJGGM19/agent.1385

DEBUG ssh: Exit status: 0

 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-4fSUJGGM19/agent.1385

DEBUG ssh: stderr: mount: 

**DEBUG ssh: stderr: can't find /var/www/drupalvm in /etc/fstab**

DEBUG ssh: stderr: 



DEBUG ssh: stdout: /sbin/init



DEBUG ssh: stderr: /sbin/init: unrecognized option '--version'



DEBUG ssh: stdout: /sbin/init



DEBUG ssh: stderr: /sbin/init: unrecognized option '--version'



DEBUG ssh: Exit status: 0

`

The problem seems to be in "can't find /var/www/drupalvm in /etc/fstab"

If I manually try to mount it in vagrant I get the same error, so it looks the /etc/fstab wasn't updated with this mount config entry.

**Comment by oxyc** [comment]
> DEBUG ssh: stderr: /sbin/init: unrecognized option '--version'

https://github.com/mitchellh/vagrant/pull/7256

The commit that got merged is https://github.com/mitchellh/vagrant/commit/61d2a50a54bcebb40aa476f8c14be8f14db2be7f. Maybe this is a Vagrant 1.8.3+ issue

**Comment by oxyc** [comment]
Also compare

> mount -o  '192.168.88.1:/Users/alesrebec/Projects/drupal-vm/bs8' '/var/www/drupalvm'

to mine

> mount -o '' 192.168.99.1:'/Users/cindy/Projects/Personal/drupal-vm' /var/www/drupalvm (sudo=true)

**Comment by oxyc** [comment]
@alesrebec it's a long shot but could you try with adding

```yaml
mount_options: ['vers=3', 'udp']
```

to your synced folder:

```yaml
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
    mount_options: ['vers=3', 'udp']
```

**Comment by oxyc** [comment]
Actually that might be it. I'm thinking this commit caused an issue when the `mount_options` is defined but just an empty list. https://github.com/mitchellh/vagrant/commit/837713c2d13139c8741607ee089dcc9fd25470f2

**Comment by mooru** [comment]
So should we downgrade to vagrant 1.8.1 for it to work

**Comment by oxyc** [comment]
Try adding a `config.yml` with this and see if it works:

```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
    mount_options: ['vers=3', 'udp']
```

I'll update Vagrant locally in a bit to see if I can reproduce it.

**Comment by oxyc** [comment]
https://github.com/mitchellh/vagrant/issues/7443

**Comment by oxyc** [comment]
Hmm setting the mount_options didn't help but I found another fix.

Before:
```
vagrant@drupalvm-project:~$ mount -v
/dev/mapper/ubuntu--vg-root on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
/dev/sda1 on /boot type ext2 (rw)
/home/vagrant/VBoxGuestAdditions_5.0.12.iso on /tmp/vbox type iso9660 (ro)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
192.168.99.1:/Users/cindy/Projects/Personal/drupal-vm on /vagrant type nfs (rw,vers=3,udp,addr=192.168.99.1)
192.168.99.1:/Users/cindy/.vagrant.d/cache/geerlingguy/ubuntu1404 on /tmp/vagrant-cache type nfs (rw,vers=3,tcp,nolock,addr=192.168.99.1)
```

After defaulting `mount_options` to `nil` instead of `[]`.

```
/dev/mapper/ubuntu--vg-root on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
/dev/sda1 on /boot type ext2 (rw)
/home/vagrant/VBoxGuestAdditions_5.0.12.iso on /tmp/vbox type iso9660 (ro)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
192.168.99.1:/Users/cindy/Projects/Personal/drupal-vm on /var/www/drupalvm type nfs (rw,vers=3,udp,addr=192.168.99.1)
192.168.99.1:/Users/cindy/Projects/Personal/drupal-vm on /vagrant type nfs (rw,vers=3,udp,addr=192.168.99.1)
192.168.99.1:/Users/cindy/.vagrant.d/cache/geerlingguy/ubuntu1404 on /tmp/vagrant-cache type nfs (rw,vers=3,tcp,nolock,addr=192.168.99.1)
```

**Comment by oxyc** [comment]
@mooru @alesrebec could you try out the PR above and test if it solves the problem for you.

**Comment by alesrebec** [comment]
@oxyc I can confirm that "drupal" directory is now created in local_path ".".
The error I got now is 

```
TASK [Ensure drupal_composer_install_dir directory has proper permissions.] ****
fatal: [bs8]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "dialout", "mode": "0755", "msg": "chown failed", "owner": "502", "path": "/var/www/drupalvm/drupal", "size": 68, "state": "directory", "uid": 502}
```

**Comment by oxyc** [comment]
@alesrebec great! That should be fixed in master already https://github.com/geerlingguy/drupal-vm/issues/726.

**Comment by mooru** [comment]
I tried do a fresh vagrant uo after destroying the VM files. i added

mount_options: []

i can now see  the drupal folder but for some reason i get errors when it get to composer install with vagrant provosion


TASK [Generate Drupal project with composer package.] **************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:29.387215", "end": "2016-06-15 13:04:41.418576", "failed": true, "rc": 1, "start": "2016-06-15 13:04:12.031361", "stderr": "    1/4:\thttp://packagist.org/p/provider-latest$e9158e7793f31773c4604e48f996e2b95990f2791f54cfaa250b4b8161afa66e.json\n    2/4:\thttp://packagist.org/p/provider-2016-04$04aa860499930debc59990582c3fae14eceb027e21ada4b99349b2f7350bbee3.json\n    3/4:\thttp://packagist.org/p/provider-2015-07$72457df4c1d5ec54522ef3835c053e7fbe6d71f51c91e20738670526cfbc5e83.json\n    4/4:\thttp://packagist.org/p/provider-2016-01$139b8d7100b47997217a8a7edf7ffb4e16c68f88507000734750f16cbc796dab.json\n    Finished: success: 4, skipped: 0, failure: 0, total: 4\nInstalling drupal-composer/drupal-project (8.x-dev 544ba79cd95cb4fca599cba586498aaf0faf2885)\n\n                              \n  [ErrorException]            \n  mkdir(): Permission denied  \n                              \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/Users/martinoru/Sites/drupal8/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=159  changed=5    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by oxyc** [comment]
You should set `mount_options` to either `['vers=3', 'udp']` or leave it as non-existent if you have the PR above. 

I'm wondering if that happened because of all the failures before. Could you try:

```sh
# This directory shouldn't exist before the provision takes place.
rm -rf /Users/martinoru/Sites/drupal8/drupal
# Re-build from scratch.
vagrant destroy -f
vagrant up
```

**Comment by mooru** [comment]
Still getting this error after doing all 

TASK [Generate Drupal project with composer package.] **************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:28.461005", "end": "2016-06-15 13:52:04.518236", "failed": true, "rc": 1, "start": "2016-06-15 13:51:36.057231", "stderr": "    1/4:\thttp://packagist.org/p/provider-latest$06d0edc46614bedc5a6c2b213df57903db4ec3f7f6eb11f4a5a584c44db6a81a.json\n    2/4:\thttp://packagist.org/p/provider-2015-10$a263673ab35f70e998ae9a1d2faf122fc5fe58a4aff6ae7ed9f6332e4f7cf79a.json\n    3/4:\thttp://packagist.org/p/provider-2016-01$e5e7baa0c8102c22f54c3628cdc62a17e288438b7572d2487af4211c6f8b1f5b.json\n    4/4:\thttp://packagist.org/p/provider-2016-04$809d7c08321ce2492bdf1a9bee4b4c07f0b910c31b74a51824bb991607d20672.json\n    Finished: success: 4, skipped: 0, failure: 0, total: 4\nInstalling drupal-composer/drupal-project (8.x-dev 544ba79cd95cb4fca599cba586498aaf0faf2885)\n\n                              \n  [ErrorException]            \n  mkdir(): Permission denied  \n                              \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by geerlingguy** [comment]
@mooru and @oxyc great progress so far!

@mooru - Can you delete the synced folder entirely (the `drupal` directory inside the Drupal VM directory), then run `vagrant reload --provision`? I hit this error last week but after doing that I haven't run into the error again.

**Comment by twerthmueller** [comment]
I expected the same problem and the PR #737 fixes it. The folder get mounted as defined.

Vagrant 1.8.4
Drupal VM 3.1.1
Virtual Box 5.0.20

**Comment by mooru** [comment]
It is working well now. I guess the mount_options solved it

**Comment by twerthmueller** [comment]
As I tried the mount_options before, it doesn't work. But now I tried it again and it works also for me.

**Comment by geerlingguy** [comment]
I'm testing #737 with 1.8.1 to make sure it doesn't cause any regressions. Once that's done I'll merge, and do a new bugfix release so this issue gets resolved. Vagrant update issues--

**Comment by geerlingguy** [comment]
To all in this issue—please try with the latest `master` version of Drupal VM. It should hopefully be fixed now. Also, I'll be tagging another bugfix release soon so you can switch back to a stable version, if that's your thing!

**Comment by geerlingguy** [comment]
This should be fixed with the latest release, 3.1.2
